import { randomBytes } from "node:crypto";

/**
 * Room codes are generated by the server, never chosen by a person.
 *
 * A teacher-chosen code is a handful of guesses wide: 六年三班, fish01, the
 * class name. Anyone who guesses one reads every nickname and every 生活困擾 in
 * that room. The codes here are drawn from a CSPRNG instead, which is what
 * makes the room code usable as the room's only credential.
 *
 * The alphabet is Crockford Base32 in lower case: no i, l, o or u. That leaves
 * no pair of characters that look alike on a projector, and it comes with
 * defined aliases for the mistakes people still make when reading one back,
 * so a student who types O for 0 or I for 1 lands in the right room instead of
 * being told the code is wrong.
 */
const ALPHABET = "0123456789abcdefghjkmnpqrstvwxyz";

/** Crockford's decoding aliases, applied to whatever a student types. */
const ALIASES = new Map<string, string>([
  ["o", "0"],
  ["i", "1"],
  ["l", "1"],
]);

/**
 * 10 characters of Crockford Base32 is 50 bits. With the failed-lookup rate
 * limit in front of it, exhausting that space is not a thing that happens.
 */
export const DEFAULT_CODE_LENGTH = 10;
export const MIN_CODE_LENGTH = 8;
export const MAX_CODE_LENGTH = 24;

/** Where the display hyphen goes. Purely cosmetic; input strips it again. */
const GROUP_SIZE = 5;

export class RoomCodeFormatError extends Error {}

export function generateRoomCode(length: number = DEFAULT_CODE_LENGTH): string {
  if (length < MIN_CODE_LENGTH || length > MAX_CODE_LENGTH) {
    throw new RangeError(`room code length must be between ${MIN_CODE_LENGTH} and ${MAX_CODE_LENGTH}`);
  }
  // 256 is a whole multiple of 32, so a byte maps onto the alphabet without
  // the modulo bias that would otherwise favour the first few characters.
  const bytes = randomBytes(length);
  let code = "";
  for (const byte of bytes) code += ALPHABET[byte % ALPHABET.length];
  return code;
}

/**
 * Canonicalises whatever a student typed: case, spacing, the display hyphen and
 * the confusable characters all collapse onto one stored form.
 *
 * Throws rather than returning null so that a malformed code and a code for a
 * room that does not exist are two different things internally, even though the
 * HTTP layer answers both without saying which.
 */
export function normalizeRoomCode(input: unknown): string {
  if (typeof input !== "string") throw new RoomCodeFormatError("room code must be a string");

  let code = "";
  for (const raw of input.toLowerCase()) {
    if (raw === "-" || raw === " " || raw === "\t") continue;
    const mapped = ALIASES.get(raw) ?? raw;
    if (!ALPHABET.includes(mapped)) throw new RoomCodeFormatError("room code contains an unusable character");
    code += mapped;
  }

  if (code.length < MIN_CODE_LENGTH || code.length > MAX_CODE_LENGTH) {
    throw new RoomCodeFormatError(
      `room code must be between ${MIN_CODE_LENGTH} and ${MAX_CODE_LENGTH} characters`,
    );
  }
  return code;
}

/** The form shown to a class, e.g. k7m2x-9qpwd. Only ever for display. */
export function formatRoomCode(code: string): string {
  const groups: string[] = [];
  for (let at = 0; at < code.length; at += GROUP_SIZE) groups.push(code.slice(at, at + GROUP_SIZE));
  return groups.join("-");
}
